### ISSUE TITLE
Payment Requirement Bug

### ISSUE THREAD

**Issue by jibranmazhar** [duffelhq/duffel-api-python#105]
Hi
Please Solve this issue
![Screenshot from 2022-02-11 02-06-12](https://user-images.githubusercontent.com/71643474/153496493-d5a5302f-f9cb-41d6-9eb6-f5590ffb73a4.png)
![Screenshot from 2022-02-11 02-06-22](https://user-images.githubusercontent.com/71643474/153496539-13b5bb4f-fb23-4abc-97d1-51ad74d893ef.png)

**Comment by jesse-c** [comment]
Hi @jibranmazhar! Do you have a small code sample that I could use to reproduce the issue? I believe I know what the issue is, but a code sample would help.

**Comment by jesse-c** [comment]
I've created a PR which fixes the issue. If you'd like to use this immediately, you can clone that branch locally and build the library from it. We're planning to release this ASAP though, so you hopefully shouldn't need to do that.

**Comment by jesse-c** [comment]
@jibranmazhar: We've just released 0.3.1 (https://github.com/duffelhq/duffel-api-python/releases/tag/0.3.1). It'll be available soon when it shows up on https://pypi.org/project/duffel-api/.

**Comment by jibranmazhar** [comment]
Hi @jesse-c Thank you so much :)
