### ISSUE TITLE
invalid_request_error: Not found: The resource you are trying to access does not exist

### ISSUE THREAD

**Issue by suledev** [duffelhq/duffel-api-python#210]
**Describe the bug**

When attempting to get an offer by its id `CLIENT.offers.get(offer_id)` I get this response:

```
invalid_request_error: Not found: The resource you are trying to access does not exist
```

This is when using both a test key and a live key 

**To Reproduce**

**Expected behavior**

**System (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Library version: [e.g. 0.2.0]
 - Python Version: [e.g. 3.10]

**Additional context**

**Comment by suledev** [comment]
My mistake, was not passing in a correct offer id.

**Comment by jesse-c** [comment]
No worries at all!
