### ISSUE TITLE
how do i add Query parameters?

### ISSUE THREAD

**Issue by asafd11** [duffelhq/duffel-api-python#211]
hello i create a python script for booking flights 
i am getting offers like this:
`    offers_list =duffel.offer_requests.create().slices(slices).passengers([{"type": "adult"}]).return_offers().execute()
id like to add query parameters for
max connections
and sort by total amount
any idea how to add it to the offer requests?

https://duffel.com/docs/api/v1/offers/get-offers
query parameters

`

**Comment by nlopes** [comment]
Hi @asafd11,

For `max_connections` you can just call it on `offer_requests` like so:
```
offers_list =duffel.offer_requests.create().slices(slices).passengers([{"type": "adult"}]).max_connections(1).return_offers().execute()
```

We don't yet offer sorting in the library I am afraid! I'll make an internal note of this.
