### ISSUE TITLE
throw ValueError: time data '2023-01-24T23:59:59.000Z' does not match format '%Y-%m-%dT%H:%M:%SZ'

### ISSUE THREAD

**Issue by asafd11** [duffelhq/duffel-api-python#212]
i am getting this error started today 
the slice is  from: JFK      to :LHR   on: 2023-01-27
offers_list =duffel.offer_requests.create().passengers([{"type": "adult"}]).slices(slices).return_offers().execute()

throw 
throw ValueError: time data '2023-01-24T23:59:59.000Z' does not match format '%Y-%m-%dT%H:%M:%SZ'

**Comment by baraayyash** [comment]
Hi, 

i am facing this issue when marking return_offers().. without it it works fine, but then i need to do a separate request to get the list of offers. 

the issue cased by this line of code
`        return OfferRequest.from_json(res["data"])
`

Can you please fix this?

**Comment by yash12392** [comment]
Facing the same error, can't believe no one from Duffel has identified this bug and is working on fixing/maintaining it.

**Comment by nlopes** [comment]
Apologies for the long reply on this one. We'll be taking a look shortly but I can replicate this so definitely a bug.

**Comment by yash12392** [comment]
Thanks @nlopes do you know when you can release the fixed version, have a client who wants to try your API but has discouraged them at the very first step of error.

**Comment by nlopes** [comment]
> Thanks @nlopes do you know when you can release the fixed version, have a client who wants to try your API but has discouraged them at the very first step of error.

I just put in a PR for this fix, should go out shortly. Thank you for your patience.

**Comment by nlopes** [comment]
This auto closed (and it is fixed in main) but I still have to release `0.4.3` which will have the fix.

**Comment by nlopes** [comment]
Version 0.4.3 has now been released with a fix.
