### ISSUE TITLE
Passenger Type Bug

### ISSUE THREAD

**Issue by jibranmazhar** [duffelhq/duffel-api-python#88]
Hi i got error in passengers model

from ..models import LoyaltyProgrammeAccount

class Passenger:
    """The passenger travelling"""

please add here `infant_without_seat` because when i search with child with age 1 in passenger response i got `infant_without_seat type` and code got Exception
    allowed_types = ["adult"]

    class InvalidType(Exception):
        """Invalid passenger type provided"""

    def __init__(self, json):
        for key in json:
            value = json[key]
            if key == "type" and value and value not in Passenger.allowed_types:
                raise Passenger.InvalidType(value)
            if key == "loyalty_programme_accounts":
                value = [
                    LoyaltyProgrammeAccount(loyalty_programme_account)
                    for loyalty_programme_account in value
                ]

            setattr(self, key, value)

**Comment by sgerrand** [comment]
Hi Jibran! Thanks for supplying the details of this error that you've encountered. Using a `type` for an infant passenger is deprecated and we suggest that you supply an `age` of 0 or 1 instead when searching for flights.

https://duffel.com/docs/api/offer-requests/create-offer-request#offer-requests-create-an-offer-request-body-parameters-passengers-passengers-passengers-age

**Comment by sgerrand** [comment]
There's a note about this in the API reference documentation but it's buried in the description of the `type` field which you were trying to use:

> If the passenger is aged 18 or over, you should specify a `type` of `adult`. If a passenger is aged under 18, you should specify their `age` instead of a `type`. A passenger can have only a `type` or an `age`, but not both.

https://duffel.com/docs/api/offer-requests/create-offer-request#offer-requests-create-an-offer-request-body-parameters-passengers-passengers-passengers-type

**Comment by sgerrand** [comment]
I hope that makes sense – let us know if you have any further queries about this!

**Comment by sgerrand** [comment]
@jibranmazhar: I've added an example of how to search and book with infant passengers in #90. Hopefully it'll be useful for you.

**Comment by jibranmazhar** [comment]
![Screenshot from 2022-02-02 03-09-58](https://user-images.githubusercontent.com/71643474/152060180-5f222383-24ac-43d0-a50f-6c96972beca9.png)

hi @sgerrand Please check this i got this error when i do and i follow the step which is documented in duffel i add children by there age like this `{'age': 1}` when i create offer and creating offer request works well but after that i call `client.offers.list()` call and see this error please help me on this.

**Comment by sgerrand** [comment]
Thanks Jibran – I'll look into this for you later on today.

**Comment by jibranmazhar** [comment]
@sgerrand OK Thanks.
